-----------------------------------------------------------------------------------------
--
-- main.lua
--
-- Created By Gillian Gonzales
-- Created On Febuary 2018
-- 
-- This file prints Hello, World! to the console 
-----------------------------------------------------------------------------------------
print ( "Hello, World!")
--  